# Codam
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/juvan-to/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/juvan-to/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception

services:
# mariadb
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
# nginx
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always
